//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stakingapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stk_admin
    {
        public int id { get; set; }
        public double reward_per_frequency { get; set; }
        public string private_key { get; set; }
        public string public_address { get; set; }
        public Nullable<double> gas_limit { get; set; }
        public string zinTokenAddress { get; set; }
        public string stkcontractAddress { get; set; }
    }
}
